#!/usr/bin/env bash
# Bash script that install and configure HAproxy

sudo apt-get -y update
sudo apt-get -y install haproxy

str_haproxy="frontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tserver 86871-web-01 52.91.126.49:80 check\n\tserver 86871-web-02 100.25.180.45:80 check"
echo -e "$str_haproxy" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart